### ISSUE TITLE
‘REDUCE_SUM’ is not a member of ‘cv’

### ISSUE THREAD

**Issue by JialingLiu-SLAM** [uzh-rpg/dslam_open#17]
/home/z/c/my_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/HSolver.cpp: In member function ‘cv::Mat DVision::HSolver::findHomography(const cv::Mat&, const cv::Mat&, double, int, std::vector<unsigned char>*, bool, double, int) const’:
/home/z/c/my_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/HSolver.cpp:144:35: error: ‘REDUCE_SUM’ is not a member of ‘cv’
       cv::reduce(sq_ab, error, 0, cv::REDUCE_SUM); // 0 = single row
                                   ^
/home/z/c/my_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/FSolver.cpp: In member function ‘cv::Mat DVision::FSolver::findFundamentalMat(const cv::Mat&, const cv::Mat&, double, int, std::vector<unsigned char>*, bool, double, int) const’:
/home/z/c/my_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/FSolver.cpp:149:35: error: ‘REDUCE_SUM’ is not a member of ‘cv’
       cv::reduce(sq_ab, norms, 0, cv::REDUCE_SUM); // 0 = single row
                                   ^
/home/z/c/my_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/FSolver.cpp:160:32: error: ‘REDUCE_SUM’ is not a member of ‘cv’
       cv::reduce(prod, dot, 0, cv::REDUCE_SUM); // dot is Nx1
                                ^
make[5]: *** [CMakeFiles/DLib.dir/src/DVision/HSolver.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: *** [CMakeFiles/DLib.dir/src/DVision/FSolver.cpp.o] Error 1
make[4]: *** [CMakeFiles/DLib.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [dlib_src-prefix/src/dlib_src-stamp/dlib_src-build] Error 2
make[1]: *** [CMakeFiles/dlib_src.dir/all] Error 2
make: *** [all] Error 2

Is this the wrong version of OpenCV? I've used opencv 2.4.11 and 2.4.8 before. It's all this error.

**Comment by rocker12121** [comment]
How did you solve this error. Can you please guide.
